pipeline:
  create_cluster:
    image: banzaicloud/ci-pipeline-client:0.10.1
    action: EnsureCluster

  prepare_deployment_package:
    when:
      branch:
        include: [master]
    image: lachlanevenson/k8s-helm:v2.11.0
    commands:
    - helm init -c
    - helm package ./.banzaicloud/charts/mysql-spotguide
    - helm repo add presslabs https://presslabs.github.io/charts
    - helm fetch presslabs/mysql-operator --version 0.1.14

  install_mysql_root_secret:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.10.1
    action: InstallSecret
    clusterSecret:
      # sourceSecretName:
      name: '{{ .CICD_REPO_NAME }}-mysql'
      namespace: default
      merge: true
      spec:
      - name: ROOT_USER
        source: username
      - name: ROOT_PASSWORD
        source: password

{{{{- if .pipeline.deploy_mysql_cluster.deployment.values.mysql.database }}}}
  install_mysql_user_secret:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.10.1
    action: InstallSecret
    clusterSecret:
      name: '{{ .CICD_REPO_NAME }}-mysql'
      namespace: default
      merge: true
      spec:
      - name: USER
        source: username
      - name: PASSWORD
        source: password
{{{{- end }}}}

{{{{- if and .pipeline.deploy_mysql_cluster.deployment.values.mysql.backup .pipeline.deploy_mysql_cluster.deployment.values.mysql.backup.enabled }}}}
  {{{{- if (and (.pipeline.deploy_mysql_cluster.deployment.values.mysql.backup.cloud) (eq .pipeline.deploy_mysql_cluster.deployment.values.mysql.backup.cloud "amazon")) }}}}
  install_backup_secret:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.10.1
    action: InstallSecret
    clusterSecret:
      # sourceSecretName:
      name: '{{ .CICD_REPO_NAME }}-backup'
      namespace: default
      merge: true
      spec:
        - name: AWS_REGION
          # value:
        - name: AWS_ACCESS_KEY_ID
          source: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_KEY
          source: AWS_SECRET_ACCESS_KEY
  {{{{- else if (and (.pipeline.deploy_mysql_cluster.deployment.values.mysql.backup.cloud) (eq .pipeline.deploy_mysql_cluster.deployment.values.mysql.backup.cloud "google")) }}}}
  install_backup_secret:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.10.1
    action: InstallSecret
    clusterSecret:
      # sourceSecretName:
      name: '{{ .CICD_REPO_NAME }}-backup'
      namespace: default
      merge: true
      spec:
        - name: GCS_LOCATION
          # value:
        - name: GCS_SERVICE_ACCOUNT_JSON_KEY
  {{{{- else if (and (.pipeline.deploy_mysql_cluster.deployment.values.mysql.backup.cloud) (eq .pipeline.deploy_mysql_cluster.deployment.values.mysql.backup.cloud "azure")) }}}}
  install_backup_secret:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.10.1
    action: InstallSecret
    clusterSecret:
      # sourceSecretName:
      name: '{{ .CICD_REPO_NAME }}-backup'
      namespace: default
      merge: true
      spec:
        - name: AZUREBLOB_LOCATION
          # value:
        - name: AZUREBLOB_KEY
          source: accessKey
        - name: AZUREBLOB_ACCOUNT
          source: storageAccount
  {{{{- end }}}}
{{{{- end }}}}

  install_phpmyadmin_control_secret:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.10.1
    action: InstallSecret
    clusterSecret:
      # sourceSecretName:
      name: '{{ .CICD_REPO_NAME }}-phpmyadmin'
      namespace: default
      merge: true
      spec:
      - name: username
        source: username
      - name: password
        source: password

  deploy_mysql_operator:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.10.1
    action: EnsureDeployment
    deployment:
      name: './mysql-operator-0.1.14.tgz'
      releaseName: mysql-operator
      reuseValues: true
      namespace: pipeline-system
      values:
        helperImage: 'banzaicloud/mysql-helper:0.1.15'
        replicaCount: 1
        rbac:
          create: true
          serviceAccountName: mysql-operator

  deploy_mysql_cluster:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.10.1
    action: EnsureDeployment
    deployment:
      name: './mysql-spotguide-0.0.2.tgz'
      reuseValues: true
      releaseName: '{{ .CICD_REPO_NAME }}'
      wait: true
      timeout: 900
      values:
        nameOverride: '{{ .CICD_REPO_NAME }}'
        mysql:
          existingSecret: '{{ .CICD_REPO_NAME }}-mysql'
          backup:
            secret: '{{ .CICD_REPO_NAME }}-backup'
        phpmyadmin:
          existingSecret: '{{ .CICD_REPO_NAME }}-phpmyadmin'
          ingress:
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/redirect-regex: ^http://(.*)
              traefik.ingress.kubernetes.io/redirect-replacement: https://$1
              traefik.ingress.kubernetes.io/redirect-permanent: "true"
            hosts:
            - 'admin-{{.CICD_REPO_NAME}}.{{.CLUSTER_NAME}}.{{.ORG_NAME}}.{{.DOMAIN_NAME}}'
